[Grupo 23] Requisitos 14, 15, 16, 17 e 18
tryber/sd-013-b-project-recipes-app pull request #283
Opened 2021-09-23 21:40 UTC by matheuscarvalhoscm

- [ ] Requisito 14 - [Card Trello](https://trello.com/c/zVHuaqNe/14-14-posicione-a-barra-logo-abaixo-do-header-e-implemente-3-radio-buttons-ingrediente-nome-e-primeira-letra)
- [ ] Requisito 15 - [Card Trello](https://trello.com/c/Xq2FyW7c/15-15-busque-na-api-de-comidas-caso-a-pessoa-esteja-na-p%C3%A1gina-de-comidas-e-na-de-bebidas-caso-esteja-na-de-bebidas)
- [ ] Requisito 16 - [Card Trello](https://trello.com/c/ymWSBozY/16-16-redirecione-para-a-tela-de-detalhes-da-receita-caso-apenas-uma-receita-seja-encontrada-com-o-id-da-mesma-na-url)
- [ ]  Requisito 17 - [Card Trello](https://trello.com/c/iOmjHzau/17-17-mostre-as-receitas-em-cards-caso-mais-de-uma-receita-seja-encontrada)
- [ ]  Requisito 18 - [Card Trello](https://trello.com/c/f44YxRmO/18-18-exiba-um-alert-caso-nenhuma-receita-seja-encontrada)

2021-09-27 20:43 UTC, Alexsander-Trybe approved these changes

2021-09-27 21:00 UTC, diogodlemos approved these changes
Boa ! #VQV

2021-09-27 21:17 UTC, luciobj requested changes
De uma olhada nos pontos comentados por favor! :rocket:

2021-09-27 21:17 UTC, luciobj commented on src/Components/SearchBar.js
> +          onChange={ (target) => handleChange(target, setSearchWord) }
Essa parte do código funciona muito bem, e está correta.
Porém, a variavel target não parece estar nomeada corretamente, uma vez que ela se refere a event, e não target.
Além disso, você poderia reescrever ele de forma a evitar um, dos dois processos feitos, se utilizasse essa sintaxe:
```suggestion
          onChange={ ({ target }) => setSearchWord(target.value)) }
```

2021-09-27 21:17 UTC, luciobj commented on src/tests/Meals.test.js
> +    const meals = {
O que você acha de colocar a chave json() neste objeto, para alinhar com o uso dessa informação pelas suas funções? :smiley:

2021-09-27 21:17 UTC, luciobj commented on src/tests/Meals.test.js
> +      expect(headerSearchButton).toBeInTheDocument();
Será que este pedaço do teste das linhas 111 a 116, precisa estar aqui novamente, para garantir o que esta testado? :question:

2021-09-27 21:28 UTC, matheuscarvalhoscm commented on src/Components/DrinksCards.js
> +  const MAX_LENGTH = 12;
Boa sugestão! Alterei essa e outras variáveis que se encaixam na sua sugestão.

2021-09-27 21:29 UTC, matheuscarvalhoscm commented on src/Components/MealsCards.js
> +  const MAX_LENGTH = 12;
Ótima idea! Alteração realizada.

2021-09-27 21:35 UTC, matheuscarvalhoscm commented on src/Components/SearchBar.js
> +          onChange={ (target) => handleChange(target, setSearchWord) }
Boa demais. Fiz a alteração seguindo sua sugestão e temos menos linhas de código.

2021-09-27 21:59 UTC, matheuscarvalhoscm commented on src/tests/Meals.test.js
> +      expect(headerSearchButton).toBeInTheDocument();
Pensando bem (e com a sua explicação), não faz sentido essas linhas se repetirem, sendo que já realizei os mesmos testes nas linhas anteriores. Boa dica!

2021-09-27 22:35 UTC, luciobj requested changes
So mais um ponto jovem! :racehorse:

2021-09-27 22:35 UTC, luciobj commented on src/tests/Meals.test.js
> +      json: () => {},
O que você acha de colocar o objeto esperado, como retorno dessa função? :smile:

2021-09-27 23:23 UTC, matheuscarvalhoscm commented on src/tests/Meals.test.js
> +      json: () => {},
Boa! Valeu pela dica e ajuda pra fazer essa alteração!

2021-09-28 18:20 UTC, luciobj approved these changes
Muito bom, bastante completo o código! :+1:

2021-09-28 18:23 UTC, merged